spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"
accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Naveen K - QA Lead"
    email: "naveenk@gmail.com"
  onCallSupport:
    +91 8967543988
    +91 7843215084